DEFAULT_CURRENCY = 'EUR'
TENANT_GROUP = 'Tenant'
LANDLORD_GROUP = 'Landlord'
DATE_INPUT_FORMATS = ['%Y-%m-%d', '%d.%m.%Y', '%d/%m/%Y']
PHONE_REGEX = r'^\+?\d{7,15}$'
MIN_BOOKING_CREATE_ADVANCE_DAYS = 7
MIN_BOOKING_CANCEL_ADVANCE_DAYS = 7
MAX_BOOKING_CREATE_ADVANCE_DAYS = 365
