# Generated by Django 6.1.1 on 2026-09-13 09:46

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='street_address',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_li_city_e45c53_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['rooms'], name='listings_li_rooms_4641e1_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['property_type'], name='listings_li_propert_7a505c_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('city', 'street_address'), name='unique_active_listing_per_address'),
        ),
    ]
