# Generated by Django 6.1.1 on 2026-09-21 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_unique_active_listing_per_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_active_listing_per_address',
        ),
        migrations.AddField(
            model_name='listing',
            name='active_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(is_deleted=False, then=models.Value(1)), default=models.Value(None), output_field=models.IntegerField()), output_field=models.IntegerField(null=True)),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('landlord', 'city', 'street_address', 'active_key'), name='unique_active_listing_per_address'),
        ),
    ]
