# Generated by Django 6.1.1 on 2026-09-13 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_street_address_alter_listing_price_and_more'),
        ('statistic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='viewhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('listing', 'user'), name='unique_listing_view_per_user'),
        ),
    ]
