# Generated by Django 6.1.1 on 2026-09-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_viewhistory_unique_listing_view_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Search Query', 'verbose_name_plural': 'Search Queries'},
        ),
    ]
