# Generated by Django 6.1.1 on 2026-09-21 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_unique_active_listing_per_address_and_more'),
        ('statistic', '0004_alter_searchquery_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viewhistory',
            name='unique_listing_view_per_user',
        ),
        migrations.AddConstraint(
            model_name='viewhistory',
            constraint=models.UniqueConstraint(fields=('listing', 'user'), name='unique_listing_view_per_user'),
        ),
    ]
